### ISSUE TITLE
TranslatePipe markForCheck - needs to happen on init as well?

### ISSUE THREAD

**Issue by NathanWalker** [ocombe/ng2-translate#61] opened 2016-03-16 18:16 UTC
The fix works great when using `OnPush` after a value has `changed`. However I'm seeing that the pipe does not transform anything when everything initializes/bootstraps from the start.

You can see this on this branch:
https://github.com/NathanWalker/angular2-seed-advanced/tree/on-push

Clone and checkout that branch, then:

```
npm install
npm start
```

You'll see that no text is translated on page to start, however if you change the language dropdown in top right, it will then fire change detection and then the pipe will transform and show all the text.

I would submit a PR to fix, but not sure what needs to be done. @ocombe hoping you know :)

**Comment by ocombe** [comment] 2016-03-20 14:36
So I check, the pipes for menu are called (and it's translated), but the pipes for the content are not called until you type in the input.
The problem is probably on your side, not on the one of this lib :)

**Comment by NathanWalker** [comment] 2016-03-20 15:28
Interesting. Thanks for checking! I'll see what I can find.

**Comment by NathanWalker** [comment] 2016-03-20 16:23
Turned out the *root* component **only** needed to use `ChangeDetectionStrategy.Default`. Every other component now uses `OnPush` and it works fine. Maybe this is to be expected, not sure, but it doesn't look like the *root* component can be `OnPush`; not that it **needs** to be, but seems like it wouldn't matter if whole tree is `OnPush` including **root**. Anyhow, solved. Thanks again.

**Comment by ocombe** [comment] 2016-03-20 19:23
Ok, good to know!

**Comment by NathanWalker** [comment] 2016-06-23 18:31
This has cropped back up in the latest 2.2.2 release. I'm going to reopen and try to create a plunkr or repo demonstrating the issue later and will post back with a link so you can see.

**Comment by ocombe** [comment] 2016-12-21 10:26
I'm using it with OnPush at work without any problem, I think I can close this. Let me know if you still have a problem and I'll reopen.

**Closed by ocombe** 2016-12-21 10:26 UTC
Labels: Priority: medium, Type: bug
