### ISSUE TITLE
translate.get(...).flatMap(...) not working in pending state

### ISSUE THREAD

**Issue by jonaszuberbuehler** [ocombe/ng2-translate#308] opened 2016-11-04 14:33 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
Not sure if it's a bug or misuse by me...

**Current behavior**
Using `translate.get('...').flatMap(...).subscribe(observer)` does not work if `this.pending` is set.

**Expected/desired behavior**
The `observer` gets called with the translation.

**Reproduction of the problem**
Made a small [plunker](http://plnkr.co/edit/smNbPyTIp8LCyVOe0YGz?p=preview). Calling `doIt()` from `ngOnInit()` does not work, calling it afterwards works just fine. Although I didn't dig too deep it looks like to be caused by `this.pending`.

**Comment by SamVerschueren** [comment] 2016-11-04 18:49
I can confirm this seems like a bug. Have to dive deeper to find the cause.

**Comment by imgx64** [comment] 2016-11-06 05:45
I submitted a PR to fix this issue. I used `mergeMap` instead of `Observable.create` and it worked. I'm not sure why, but the `Observable.create` closure was being called with a stopped `observer`.

**Comment by imgx64** [comment] 2016-11-06 06:32
Ok, I found the root issue. `getTranslation` was using `share()` which was creating a hot observable, and then immediately subscribing to it. Once this subscription was done, the `pending` observable stopped because there are no more subscribers. Any subscribers afterwards were ignored.

**Comment by ocombe** [comment] 2016-11-10 09:43
There's a good reason for adding the share, otherwise it will request multiple times the json file from the server (or anything else that a custom loader can do) if you have multiple translations on your page. Imagine a page with 10 translated words, then it would make 10 http requests.
I'll take a look at the problem but removing share is not an option.

**Comment by imgx64** [comment] 2016-11-10 11:02
`TranslateService.getTranslation` gets called only once the first time a language is used (or if you explicitly call it or call `reloadLang`). It doesn't get called for every translated word.

But even if `getTranslation` is called multiple times, it would still do multiple HTTP requests even with the `share`, because it's creating a new observable every time it's called, not reusing the `share`d observable.

I don't think `share` is what you want. [`share` uses `refCount`](https://github.com/ReactiveX/rxjs/blob/master/src/operator/share.ts#L22), so once all subscriptions are done, the shared observable unsubscribes from the original (http) observable and stops emitting. Any observers that subscribe afterwards simply never get called (neither onNext nor onComplete).

**Comment by imgx64** [comment] 2016-11-20 09:31
Okay. I found the **root** *root* root issue!

It's a bug in RxJS (https://github.com/ReactiveX/rxjs/issues/2145) that affects hot observables. I've added a PR that fixes this bug without removing the `share()`.

**Comment by ocombe** [comment] 2016-11-20 10:37
Thanks a lot for taking the time to find another solution and submitting a PR, I've merged it!

**Closed** 2016-11-20 10:36 UTC
Labels: Type: bug
