### ISSUE TITLE
Providing TranslateModule with a factory doesn't work with ngc

### ISSUE THREAD

**Issue by Kobzol** [ocombe/ng2-translate#247] opened 2016-09-28 20:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When I tried to provide TranslateStaticLoader using a function, ngc complains that function calls are not supported. I thus moved the function to an exported function (and this actually helped me with the same error with another library), but it didn't help with TranslateModule.
```javascript
export function createTranslateLoader(http: Http)
{
    return new TranslateStaticLoader(http, '/assets/i18n', '.json');
}

@NgModule({
    imports: [
        IonicModule.forRoot(Application),
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: createTranslateLoader,
            deps: [Http]
        }),
    ], ...
```
This gives me the error `Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`. If I remove the TranslateModule, the error disappears. Do you have any idea how to solve this?

**Please tell us about your environment:**

* **ng2-translate version:** x.x.x
2.5.0

* **Angular version:** 2.0.0-rc.X
2.0.1 (Ionic 2 rc.0)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
Typescript 2.0

**Comment by ocombe** [comment] 2016-09-29 07:14
I'm closing it as it is a duplicate of https://github.com/ocombe/ng2-translate/issues/218
the problem is that the lib is not compatible with AoT *yet*. I've talked with the angular team a bit these past days (at angular connect and on slack), and if you want a lib to be compatible with AoT you have to precompile it before shipping it on npm.
I'll do that and then it should work for you

**Closed by ocombe** 2016-09-29 07:14 UTC
