### ISSUE TITLE
Cannot use with rxjs 5.0.0-beta.2

### ISSUE THREAD

**Issue by cristi-badila** [ocombe/ng2-translate#82] opened 2016-04-04 08:29 UTC
I tried updating today to the latest version of ng2-translate but my app fails when ng2-translate tries to load `/rxjs/add/observable/of`. This module was properly added only in rxjs 5.0.0-beta3. 

You can compare the main `Rx` files:

- https://github.com/ReactiveX/rxjs/blob/5.0.0-beta.2/src/Rx.ts
- https://github.com/ReactiveX/rxjs/blob/5.0.0-beta.3/src/Rx.ts

The issue was introduced in https://github.com/ocombe/ng2-translate/commit/4b78732e. I'm using rxjs `5.0.0-beta.2` as angular2.0.0-beta13 uses this exact same version.

**Comment by ocombe** [comment] 2016-04-04 08:31
Thanks, someone reported a problem yesterday but he was using RxJS beta 4 and it worked after he downgraded to beta 2, that's weird that you have this problem on beta 2, I'll check asap.

**Comment by webprofusion-chrisc** [comment] 2016-04-06 12:11
I've had similar trouble, I think the package needs to reference ^5.0.0-beta.2 or ~5.0.0? Otherwise it has a hard dependency on the older beta version.

**Comment by fuitattila** [comment] 2016-04-06 15:31
I have the same issue. Are there any temporary hot fixes?

**Comment by KevensPronovost** [comment] 2016-04-12 13:18
Hi, we've encountered the same problem. In my case my app still boots and the translation are done, but I get an error on runtime: Uncaught ReferenceError: require is not defined.
As requested by others, I would also like to know if there is a planned fix until angular upgrade RxJS version? Even though it is functionnal, an error is a blocker for prod. Thank you! And thanks for this great library.

**Comment by ocombe** [comment] 2016-04-15 09:03
Observable.of is added to Observable by calling `import 'rxjs/add/observable/of';`.

I just released a new version that removed most peer dependencies, included the dependency to RxJS. It's still a dependency but since I use the same as Angular 2, I don't need to specify it (I think).
Let me know if it fixes some of your problems ?

**Comment by KevensPronovost** [comment] 2016-04-15 12:47
As said it the first comment, observable.of is not imported in 5.0.0-beta.2
I tried removing my ugly patch and fails again on the same error.
Note that I use Observable.of in my app and it works fine, even with me registering the dummy, so the import must not be the way it is used in beta2.

**Comment by ocombe** [comment] 2016-04-15 12:55
Well I don't know what to tell you, but RxJS 5.0.0-beta.2 has `rxjs/add/observable/of` on npm, just check on npmcdn: https://npmcdn.com/rxjs@5.0.0-beta.2/add/observable/of.js
And I reinstalled it locally after doing `npm cache clean` just to be sure.

**Comment by KevensPronovost** [comment] 2016-04-15 12:59
It has the functionnality, but is not used. The Observable 'class' already have a static method of. It was changed in beta3. The only thing it means is that you simply don't need to import it, or in your case, require it.

And a quick search in the minimed rxjs beta2 file shows that it is not there. Perhaps they fixed it, without fixing the minified file. I'll do some tests today.

**Comment by ocombe** [comment] 2016-04-15 13:00
Okay, then can you make a PR to fix it? if it passes the tests I'll merge it :)

**Comment by ocombe** [comment] 2016-04-15 13:03
By the way, I think that just adding this line should make it work for systemjs: https://github.com/ocombe/ng2-play/blob/ng2-translate/index.html#L27

**Comment by KevensPronovost** [comment] 2016-04-15 13:05
I did, but I'm not using `/node_modules/rxjs/bundles/Rx.js`. I'm using `/node_modules/rxjs/bundles/Rx.min.js`

**Comment by ocombe** [comment] 2016-04-15 13:06
Ok, it makes sense then. That's why I like webpack much better, it bundles just what it needs :-)

**Comment by KevensPronovost** [comment] 2016-04-15 13:26
I created a pull request. I did test it on my own, and did automated test on my project, but running npm test on the fork of ng2-translate resulted in `error TS6053: File 'typings/main.d.ts' not found.`

Not sure what I'm missing, and the checks do not pass...

**Comment by gaetancollaud** [comment] 2016-04-18 12:16
I have the same issue.

For the moment, the work around of @KevensPronovost works : 
```javascript
System.register('rxjs/add/observable/of', [], function(dummy) { return { setters: [], execute: function() {dummy('default', null); }}});
```

**Comment by clothesptit** [comment] 2016-04-20 03:39
i added patch: `System.register('rxjs/add/observable/of', [], function(dummy) { return { setters: [], execute: function() {dummy('default', null); }}});` in index.html

It work . But when i change language two time i get error : EXCEPTION: TypeError: Observable_1.Observable.of is not a function

 Anyone help me to fix this issue, please ?

**Comment by KevensPronovost** [comment] 2016-04-21 13:10
It seems my patch works only because we are not using the part of the code that makes uses of rxjs/add/observable/of. The problem is it is not in the rxjs minified version, so the require fails without the patch. Hopefully, angular will upgrade rxjs version soon enough, so that we can move on to the corrected version too.

**Comment by ocombe** [comment] 2016-04-29 08:41
Angular beta 17 now uses RxJS beta 6 ! Does this fixes your problems ?

**Comment by KevensPronovost** [comment] 2016-04-29 12:50
It should, we'll upgrade today or next monday and tell you the verdict

**Comment by KevensPronovost** [comment] 2016-05-02 15:54
The issues seems to be solved. Patch removed and everything works perfectly. Still need to port the rest of our app to angular, so not in prod yet, but I'd say the issue is fixed.

**Comment by gaetancollaud** [comment] 2016-05-04 07:51
I confirm the issue is solved. I just tested. You can close this issue.

**Comment by ocombe** [comment] 2016-05-04 11:52
Cool thanks!

**Closed by ocombe** 2016-05-04 11:52 UTC
Labels: Priority: high, Status: need to check, Type: bug

**Comment by Yugloocamai** [comment] 2017-07-13 17:30
in my case I was importing JUST Observable 
`import { Observable } from 'rxjs/Observable';`
so I needed to add "of"
`import 'rxjs/add/observable/of';`
