### ISSUE TITLE
Cross Reference within language file not wokring

### ISSUE THREAD

**Issue by antonycooper** [ocombe/ng2-translate#179] opened 2016-07-29 07:57 UTC
I have been using https://github.com/angular-translate/angular-translate for some time and have a well developed language file where we cross reference other elements within the file, i.e.

"PLACEHOLDER": {
    "USERNAME": "Enter your email"
},
"LABEL": {
    "EMAIL": "@:PLACEHOLDER.USERNAME"
}

So when we use {{ 'LABEL.EMAIL' | translate }} it actually uses the text within PLACEHOLDER.USERNAME

This does not work with when I implement in angular 2.
Can anyone tell me if this is working?

**Comment by ocombe** [comment] 2016-08-13 12:42
Hello, sorry the placeholders don't work in ng2-translate, but it would be a nice PR if you have some time to do it :)

**Comment by ocombe** [comment] 2016-09-23 09:33
This is actually a duplicate of https://github.com/ocombe/ng2-translate/issues/147, closing this one, follow the status in the other one.

**Closed by ocombe** 2016-09-23 09:33 UTC
Labels: Priority: low, Status: help wanted, Type: feature
