### ISSUE TITLE
AOT compiler

### ISSUE THREAD

**Issue by bmurali31** [ocombe/ng2-translate#237] opened 2016-09-15 16:24 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
AOT compiler does not work if I use **TranslateModule.forRoot()** in the module import

**Expected/desired behavior**
**TranslateModule.forRoot()** should work with ngc compiler

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:btpW3l0jr5beJVjohy1Q).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ng2-translate version:** 2.5.0

* **Angular version:** 2.0.0
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0.2]

**Comment by frederikschubert** [comment] 2016-09-20 12:46
Duplicate of https://github.com/ocombe/ng2-translate/issues/218

**Closed** 2016-09-20 12:47 UTC
Labels: Status: duplicate, Type: bug
