### ISSUE TITLE
TypeError Cannot read property toString() of undefined

### ISSUE THREAD

**Issue by francois-appliware** [ocombe/ng2-translate#108] opened 2016-04-28 14:12 UTC
Hi,

I am trying to get ng2-translate on my website but can't get it working.

I am using angular 2 beta 16, SystemJS and gulp.
Here is my configuration of my System.config : 

    System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'ng2-translate': { defaultExtension: 'js'}
            },
            map: {
                'ng2-translate': 'lib/ng2-translate/bundles'
            }
        });

The path "lib" comes from my gulp task that copy the needed scripts to a lib folder, here it is 

    return gulp.src([
            'es6-shim/es6-shim.min.{js,map}',
            'systemjs/dist/system-polyfills.{js,*.map}',
            'angular2/bundles/angular2-polyfills.{js,*.map}',
            [ ... ]
            'ng2-translate/bundles/ng2-translate.js',
            'ng2-translate/src/*.js'
        ], {
            cwd: 'node_modules/**'
        })
        .pipe(gulp.dest(paths.libs));

I created a translation providers to get a translation from a json file :

    import {provide} from 'angular2/core';
    import {Http} from 'angular2/http';

    import {TranslateLoader, TranslateStaticLoader, TranslateService} from 'ng2-translate/ng2-translate';

    let translateLoaderFactory = (http: Http) => {
        return new TranslateStaticLoader(http, 'assets/i18n', '.json');
    }

    export let TRANSLATION_PROVIDERS: Array<any> = [
        provide(TranslateLoader, {
            useFactory: translateLoaderFactory,
            deps: [Http]
        }),
        TranslateService
    ];

And then, I put the provider in my boot.ts :

    import {TRANSLATION_PROVIDERS} from './providers/translation.provider';
    import {MainComponent} from './components/main.component';

    bootstrap(MainComponent, [
        HTTP_PROVIDERS,
        ROUTER_PROVIDERS,
        provide(LocationStrategy, { useClass: HashLocationStrategy }),
       [ ... ]
        TRANSLATION_PROVIDERS
    ]);

Unfortunately my application does not boot anymore and gives me the following error :
angular2-polyfills.js:349 Error: TypeError: Cannot read property 'toString' of undefined

From what I tried and understood, the import in my providers return "undefined" objects (TranslateLoader, TranslateService, TranslateStaticLoader).
And so, the TRANSLATION_PROVIDERS provides undefined services, and so the angular framework crashes.

How can I change that ? Where did I do wrong ? Is it from the new realeased version ?

Thank you very much!

**Comment by andzhik** [comment] 2016-05-10 19:15
Have you found a solution? I have something similar (issue #119)

**Comment by francois-appliware** [comment] 2016-05-11 12:53
I haven't.
I stopped using this module for now.

**Comment by lelezeus88** [comment] 2016-06-21 10:05
Have the same issue using SystemJS Builder.

**Comment by ocombe** [comment] 2016-06-30 21:50
Closing this as it is a duplicate of https://github.com/ocombe/ng2-translate/issues/119, you can follow the issue there.

**Closed by ocombe** 2016-06-30 21:50 UTC
