### ISSUE TITLE
Including ts source file inside npm package would be problematic

### ISSUE THREAD

**Issue by shadow999** [ocombe/ng2-translate#32] opened 2016-02-10 22:09 UTC
Hey,

I upgraded to v1.6.4 and the new version includes ts source files inside npm package. And I found that my typescript compiler would actually try to compile the ts files. With this version, the typescript compiler is actually messing up with the output path since it considered the folder contains node_modules folder is the root folder which is actually not.

I also took a look at the npm package structure of angular 2. They did not have ts files along with those d.ts files. And the main d.ts file would only export other d.ts files not ts files.

I am wondering if you guys can change the structure of bundled npm package?

Thanks.

**Comment by ocombe** [comment] 2016-02-11 06:44
Hello,

I was afraid that it might be a problem.
I did that because it was necessary to make it work with angular cli (/ping @jkuri).
What version of typescript do you use?
Do you exclude the "node_modules" folder in your tsconfig.json ?

**Comment by shadow999** [comment] 2016-02-11 06:46
@ocombe I am using tsc with version 1.7.5. And I exclude node_modules folder. Is it possible to put ts files aside d.ts files and make it work with ng-cli as well?

**Comment by ocombe** [comment] 2016-02-11 06:48
No, but I will exclude the ts files if necessary, it the angular cli that should work with .d.ts files instead.

**Comment by shadow999** [comment] 2016-02-11 06:49
@ocombe If ng-cli works with d.ts, it would be great then.

**Comment by jkuri** [comment] 2016-02-11 06:49
Hi. I will make a fix on the angular-cli to work with .d.ts files this weekend.

**Comment by ocombe** [comment] 2016-02-11 06:50
Awesome, thanks :)

**Comment by ocombe** [comment] 2016-02-11 07:29
In the mean time I'm curious about your setup @shadow999 because I don't have this problem with my projects, is your code available somewhere for me to investigate why there is a difference ?

**Comment by shadow999** [comment] 2016-02-11 07:42
root
  |- app
    |- modules
       |- <my ts files/folders>
  |- node_modules
  |- tsconfig.json

Inside tsconfig.json, I set root directory to be app/modules. And exclude node_modules in tsconfig. I also use gulp to manage compiled ts files. 

Normally, compiled ts files would not be inside app/modules folder which is following the tsconfig. However, with latest ng2-translate, compiled ts files would be under app/modules, which means tsc considered my project root folder is the root folder for all ts files.

**Comment by gruenebe** [comment] 2016-02-12 10:59
I am using this setup: https://github.com/AngularClass/angular2-webpack-starter
Which uses webpack + tsd.

I am getting some errors when I try to use ng2-translate. Maybe I am doing something wrong, so I would appreciate any help :smile: 

In my `app.ts` https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.ts
```
import {TranslateService, TranslatePipe} from 'ng2-translate/ng2-translate';
...
@Component({
  selector: 'app',
  providers: [ ...FORM_PROVIDERS, TranslateService ],
  directives: [ ...ROUTER_DIRECTIVES, RouterActive ],
  pipes: [TranslatePipe],
...
export class App {
  name = 'Foo';
  constructor(translate: TranslateService) {
      //translate.setDefaultLang('en');
      //translate.useStaticFilesLoader('assets/i18n/', '.json');
  }
}
```

I get the following error in the browser:

![image](https://cloud.githubusercontent.com/assets/12599965/13004992/43dc0dae-d17f-11e5-997d-5f99de12a45d.png)

When I try to configure translationService like this:
```
  constructor(translate: TranslateService) {
      translate.setDefaultLang('en');
      translate.useStaticFilesLoader('assets/i18n/', '.json');
  } 
```

I get these errors:
![image](https://cloud.githubusercontent.com/assets/12599965/13005068/bf0f1548-d17f-11e5-9c69-127fb7c7157c.png)

Maybe you could have a look at the `angular2-webpack-starter` and try to use ng2-translate with it?
I would really appreciate it.

**Comment by ocombe** [comment] 2016-02-12 11:04
I'll take a look at it tomorrow, in the mean time can you try version 1.6.3
please?

Le ven. 12 févr. 2016 11:59, Bernard Greenwood <notifications@github.com> a
écrit :

**Comment by gruenebe** [comment] 2016-02-12 12:10
Ok thx. I tried v1.6.3 and get the same errors. I think it is because the webpack build requires the ts files to be named withozt `.d.ts` and I don't know where to set 
```
System.config({
    packages: {
        "/ng2-translate": {"defaultExtension": "js"}
    }
});
```
And take your time, I am in no rush. I like your plugin very much.

**Comment by syrix** [comment] 2016-02-16 04:27
Hi,

thanks for this awesome library :)
I am also using this setup: https://github.com/AngularClass/angular2-webpack-starter and get the same warnings as gruenebe.

That being said, I can use your library just fine. As reference for gruenebe: I'm not using the StaticFilesLoader and my app.ts has this constructor:
```
constructor(translate: TranslateService) {
    translate.setDefaultLang('en');
    translate.setTranslation('en', {
      "test": "A test string",
      "test2": "Another test string"
    });
    var user_lang = 'en';
    translate.use(user_lang);
}
```

Apparently the warnings are caused by source maps that reference non existing files. See [this issue](https://github.com/ReactiveX/RxJS/issues/1089) for a similar problem with RxJS which is referenced by [an issue in angular2-seed](https://github.com/angular/angular2-seed/issues/19).

The source maps for ng2-translate, e.g. ng2-translate.js.map, reference typescript files, e.g. ' "sources":["ng2-translate.ts"] '. However, those *.ts-files are not included in the npm-package which leads to warnings during the build.
A quick fix for this problem is to just delete the reference to the source maps at the bottom of all *.js files in node_modules/ng2-translate, which is a very bad idea for obvious reasons.

Would it be possible for you to fix the source maps by adding the referenced *.ts files to the npm-package?
If that is not possible, could you maybe just exclude the source maps from the package?

Thanks a lot for your work. If you need any more input to resolve this isssue, just let me know :)

**Comment by ocombe** [comment] 2016-02-16 07:29
I cannot include the *.ts files because it will cause a problem for some build tools.
I took a look at angular 2 and they inline the sourcemaps (which is the easiest way to do it).
RxJS seem to have decided to change de source root and to copy source files to a new folder at build time (I don't really like that).

I might switch to inline sourcemaps. Since Angular 2 requires build tools anyway, the size of the lib is not an issue because people can just choose to do whatever they want with the lib after that (the build tools will write new vendor files with or without the sourcemaps, depending on what people choose).

**Closed** 2016-02-16 21:26 UTC
Labels: bug
