### ISSUE TITLE
Pipe not interpreting translation event ?

### ISSUE THREAD

**Issue by NicolasDucom** [ocombe/ng2-translate#89] opened 2016-04-11 13:15 UTC
Hi!,
I'm currently integrating ng2-translate on an Angular2 app, and I'm having a bit of trouble : 

In order to change my language on a button click : I call the use() function defined in the translateService. Some elements on my page use the service.get() function directly and they are translated with no problem, however, all the elements on my page using the TranslatePipe only get translated on the first language change (fr=>en or en=>fr), if I try to change my language again : only the elements using the service directly get translated. 

I added some debug info in the onLangChange listener in the TranslatePipe class and it does catch the event with event.lang updated.

Am I doing something wrong ?

**Comment by ocombe** [comment] 2016-04-11 13:20
No idea without the code :)
I'd have to check on my own to see if I have the same problem.

**Comment by NicolasDucom** [comment] 2016-04-11 13:29
Thanks for your incredibly quick answer ! :+1: 
Ok, in my service I call : `this.translate.use(this.CURRENT_LANGUAGE); //translate being the translate service`

In the translatePipe, I added : 
```
        this.onLangChange = this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
            console.log('pipe lang changed ! event:');
            console.log(event); //Language here is updated 
            this.updateValue(query, interpolateParams);
        });
```

and : 

```
    updateValue(key: string, interpolateParams?: Object): void {
        this.translate.get(key, interpolateParams).subscribe((res: string) => {
            console.log('update value! key:'+key+' res:'+res); //Translations here are still old ones
            this.value = res ? res : key;
            this._ref.markForCheck();
        });
    }
```

Don't know if that helps in any way ^^

**Comment by ocombe** [comment] 2016-04-11 13:56
Do you use any specific change detection strategy (like OnPush) ?

**Comment by NicolasDucom** [comment] 2016-04-11 14:38
No I don't have any change detection strategy, interesting fact, I'm having the problem on a Mac (Chrome), and a colleague is on Windows and doesn't seem to have any issues.

**Comment by ocombe** [comment] 2016-04-15 08:53
So this is a duplicate of https://github.com/ocombe/ng2-translate/issues/90 (yup you posted it first, but anyway), can you follow up in the other bug please?

**Closed by ocombe** 2016-04-15 08:53 UTC
Labels: Status: duplicate, Status: need to check
